# Generated by Django 3.0.5 on 2020-05-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='tick',
            field=models.BooleanField(default=False),
        ),
    ]
