# Generated by Django 3.0.5 on 2020-05-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_listitem_tick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='item_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='quantity',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
