# Generated by Django 3.0.5 on 2020-05-03 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200502_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Lista zakupów',
                'verbose_name_plural': 'Listy zakupów',
            },
        ),
        migrations.AlterModelOptions(
            name='listitem',
            options={'verbose_name': 'Pozycja z listy', 'verbose_name_plural': 'Pozycje z listy'},
        ),
        migrations.AddField(
            model_name='listitem',
            name='shopping_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ShoppingList'),
        ),
    ]
